[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[build]
  base = "/"
  command = "chmod +x build.sh && ./build.sh"
  publish = "static_build"

[build.environment]
  NEXT_IGNORE_ESLINT = "true"
  NEXT_IGNORE_LINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_IGNORE_TYPECHECK = "1"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.openai.com;"

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
